VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsPrjInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public lRow As Long
Public ProjCode As String
Public ProjName As String
Public DeliveryLeader As String
Public ActivationStatus As String
Public Category As String
Public Status As String
Public DetStatus As String
Public RevBL As String
Public IYNE As String
Public RepNE As String
Public ImpDate As String
Public IYBudget As String
Public IYRevisedBL As String
Public YTDActuals As String
Public PM As String




